# Generated by Django 3.2.9 on 2021-11-19 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_title_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
